// scripts/games.js
const gameData = [
    { id: 1, title: "Elden Ring", price: 59.99, discount: 20, image: "assets/game1.jpg", category: "action", rating: 5, desc: "Rise as the Tarnished to wield the Elden Ring's power in a vast, perilous world." },
    { id: 2, title: "Tides of Annihilation", price: 49.99, discount: 0, image: "assets/game2.jpg", category: "action", rating: 4, desc: "Battle through a post-apocalyptic wasteland to carve your destiny." },
    { id: 3, title: "World War Z: Aftermath", price: 39.99, discount: 35, image: "assets/game3.jpg", category: "adventure", rating: 3, desc: "Face hordes of undead in a gripping fight for survival." },
    { id: 4, title: "Assassin's Creed Mirage", price: 49.99, discount: 10, image: "assets/game4.jpg", category: "adventure", rating: 4, desc: "Sneak through ancient Baghdad as a master assassin." },
    { id: 5, title: "Assassin's Creed Shadows", price: 69.99, discount: 0, image: "assets/game5.jpg", category: "adventure", rating: 4, desc: "Master stealth and combat as a shinobi in feudal Japan." },
    { id: 6, title: "Assassin's Creed Valhalla", price: 59.99, discount: 40, image: "assets/game6.jpg", category: "adventure", rating: 4, desc: "Lead your Viking clan to glory in a brutal open world." },
    { id: 7, title: "Ghost of Yotei", price: 69.99, discount: 0, image: "assets/game7.jpg", category: "adventure", rating: 5, desc: "Explore a breathtaking samurai saga on Mount Yotei." },
    { id: 8, title: "Baldur's Gate 3", price: 59.99, discount: 15, image: "assets/game8.jpg", category: "rpg", rating: 5, desc: "Unleash your fate in a rich, choice-driven fantasy realm." },
    { id: 9, title: "Black Myth: Wukong", price: 59.99, discount: 10, image: "assets/game9.jpg", category: "rpg", rating: 4, desc: "Journey as the Destined One in a mythic action epic." },
    { id: 10, title: "Call of Duty: Black Ops 6", price: 69.99, discount: 5, image: "assets/game10.jpg", category: "action", rating: 4, desc: "Dive into intense, high-stakes military combat." },
    { id: 11, title: "Call of Duty: Modern Warfare 2 (2022)", price: 59.99, discount: 25, image: "assets/game11.jpg", category: "action", rating: 4, desc: "Engage in relentless warfare with elite operatives." },
    { id: 12, title: "Cities: Skylines II", price: 49.99, discount: 20, image: "assets/game12.jpg", category: "simulation", rating: 4, desc: "Build and manage your dream city from the ground up." },
    { id: 13, title: "Cyberpunk 2077", price: 59.99, discount: 50, image: "assets/game13.jpg", category: "rpg", rating: 4, desc: "Live as a cyber-enhanced outlaw in Night City's neon streets." },
    { id: 14, title: "Days Gone", price: 39.99, discount: 60, image: "assets/game14.jpg", category: "action", rating: 3, desc: "Ride through a zombie-infested world as a lone survivor." },
    { id: 15, title: "Diablo IV: Vessel of Hatred", price: 69.99, discount: 10, image: "assets/game15.jpg", category: "rpg", rating: 4, desc: "Confront darkness in a grim, loot-filled odyssey." },
    { id: 16, title: "EA Sports FC 24", price: 69.99, discount: 40, image: "assets/game16.jpg", category: "sports", rating: 4, desc: "Score goals and dominate the pitch in ultimate soccer." },
    { id: 17, title: "Far Cry 6", price: 59.99, discount: 50, image: "assets/game17.jpg", category: "adventure", rating: 4, desc: "Fight a tyrant in a tropical paradise turned warzone." },
    { id: 18, title: "Final Fantasy XVI", price: 69.99, discount: 15, image: "assets/game18.jpg", category: "rpg", rating: 4, desc: "Wield Eikon powers in a dark, epic fantasy tale." },
    { id: 19, title: "Ghost of Tsushima", price: 59.99, discount: 25, image: "assets/game19.jpg", category: "action", rating: 5, desc: "Forge a samurai legend amidst a Mongol invasion." },
    { id: 20, title: "Ghostrunner", price: 29.99, discount: 70, image: "assets/game20.jpg", category: "action", rating: 4, desc: "Slash through a cyberpunk dystopia at breakneck speed." },
    { id: 21, title: "God of War: Ragnarok", price: 69.99, discount: 20, image: "assets/game21.jpg", category: "adventure", rating: 5, desc: "Join Kratos and Atreus in a mythic Norse showdown." },
    { id: 22, title: "Grand Theft Auto V", price: 39.99, discount: 60, image: "assets/game22.jpg", category: "action", rating: 5, desc: "Rule the streets of Los Santos in a crime-fueled saga." },
    { id: 23, title: "Grand Theft Auto VI", price: 69.99, discount: 0, image: "assets/game23.jpg", category: "action", rating: 5, desc: "Explore a vibrant underworld in the next GTA chapter." },
    { id: 24, title: "Hogwarts Legacy", price: 59.99, discount: 30, image: "assets/game24.jpg", category: "adventure", rating: 5, desc: "Cast spells and uncover magic in the Wizarding World." },
    { id: 25, title: "Kong: Survivor Instinct", price: 39.99, discount: 15, image: "assets/game25.jpg", category: "action", rating: 3, desc: "Survive as Kong in a primal, action-packed adventure." },
    { id: 26, title: "Marvel's Spider-Man 2", price: 69.99, discount: 10, image: "assets/game26.jpg", category: "adventure", rating: 5, desc: "Swing through NYC as Spider-Men against a symbiote threat." },
    { id: 27, title: "Microsoft Flight Simulator 2024", price: 69.99, discount: 5, image: "assets/game27.jpg", category: "simulation", rating: 4, desc: "Soar across the globe in a stunning flight experience." },
    { id: 28, title: "Need for Speed Heat", price: 59.99, discount: 75, image: "assets/game28.jpg", category: "sports", rating: 4, desc: "Race by day, evade the law by night in high-speed chases." },
    { id: 29, title: "No Man's Sky", price: 59.99, discount: 50, image: "assets/game29.jpg", category: "adventure", rating: 4, desc: "Discover endless planets in a boundless sci-fi universe." },
    { id: 30, title: "Red Dead Redemption 2", price: 59.99, discount: 60, image: "assets/game30.jpg", category: "adventure", rating: 5, desc: "Live as an outlaw in a breathtaking Wild West epic." },
    { id: 31, title: "Wuthering Waves", price: 39.99, discount: 20, image: "assets/game31.jpg", category: "rpg", rating: 3, desc: "Unravel mysteries in a vibrant, wave-swept world." },
    { id: 32, title: "Sid Meier's Civilization VII", price: 69.99, discount: 0, image: "assets/game32.jpg", category: "strategy", rating: 4, desc: "Build an empire to stand the test of time." },
    { id: 33, title: "Sifu", price: 39.99, discount: 50, image: "assets/game33.jpg", category: "action", rating: 4, desc: "Master kung fu in a relentless quest for vengeance." },
    { id: 34, title: "Silent Hill 2", price: 59.99, discount: 15, image: "assets/game34.jpg", category: "adventure", rating: 4, desc: "Face haunting horrors in a foggy, cursed town." },
    { id: 35, title: "Street Fighter 6", price: 59.99, discount: 20, image: "assets/game35.jpg", category: "action", rating: 5, desc: "Step into the ring with next-gen fighting action." },
    { id: 36, title: "Suicide Squad: Kill the Justice League", price: 69.99, discount: 30, image: "assets/game36.jpg", category: "action", rating: 3, desc: "Take down heroes as a chaotic villain squad." },
    { id: 37, title: "Tekken 8", price: 69.99, discount: 10, image: "assets/game37.jpg", category: "action", rating: 4, desc: "Unleash combos in the ultimate fighting showdown." },
    { id: 38, title: "The Elder Scrolls V: Skyrim", price: 39.99, discount: 70, image: "assets/game38.jpg", category: "rpg", rating: 5, desc: "Slay dragons and shape your legend in Tamriel." },
    { id: 39, title: "Watch Dogs: Legion", price: 59.99, discount: 60, image: "assets/game39.jpg", category: "adventure", rating: 3, desc: "Hack and rebel in a dystopian London uprising." },
    { id: 40, title: "WWE 2K25", price: 69.99, discount: 5, image: "assets/game40.jpg", category: "sports", rating: 4, desc: "Step into the ring with wrestling's biggest stars." },
    { id: 41, title: "The Witcher 3: Wild Hunt", price: 39.99, discount: 75, image: "assets/game41.jpg", category: "rpg", rating: 5, desc: "Hunt monsters as Geralt in a sprawling fantasy epic." },
    { id: 42, title: "Overwatch 2", price: 39.99, discount: 20, image: "assets/game42.jpg", category: "action", rating: 4, desc: "Team up for fast-paced hero-based combat." },
    { id: 43, title: "Counter-Strike 2", price: 0.00, discount: 0, image: "assets/game43.jpg", category: "action", rating: 5, desc: "Master precision in the iconic tactical shooter." },
    { id: 44, title: "Dota 2", price: 0.00, discount: 0, image: "assets/game44.jpg", category: "strategy", rating: 5, desc: "Command heroes in the ultimate MOBA battlefield." },
    { id: 45, title: "League of Legends", price: 0.00, discount: 0, image: "assets/game45.jpg", category: "strategy", rating: 5, desc: "Dominate the Rift in this legendary MOBA." },
    { id: 46, title: "Valorant", price: 0.00, discount: 0, image: "assets/game46.jpg", category: "action", rating: 5, desc: "Outsmart foes in a stylish tactical shooter." },
    { id: 47, title: "Apex Legends", price: 0.00, discount: 0, image: "assets/game47.jpg", category: "action", rating: 4, desc: "Drop in and conquer in a dynamic battle royale." },
    { id: 48, title: "Fortnite", price: 0.00, discount: 0, image: "assets/game48.jpg", category: "action", rating: 4, desc: "Build and battle in the ever-evolving royale." },
    { id: 49, title: "Minecraft", price: 26.95, discount: 0, image: "assets/game49.jpg", category: "adventure", rating: 5, desc: "Craft your world in a limitless sandbox adventure." },
    { id: 50, title: "Stardew Valley", price: 14.99, discount: 30, image: "assets/game50.jpg", category: "simulation", rating: 5, desc: "Farm, fish, and find love in a charming valley." },
    { id: 51, title: "Hollow Knight", price: 14.99, discount: 50, image: "assets/game51.jpg", category: "adventure", rating: 5, desc: "Explore a hauntingly beautiful underground realm." },
    { id: 52, title: "Hades", price: 24.99, discount: 40, image: "assets/game52.jpg", category: "action", rating: 5, desc: "Defy death in a rogue-like Greek myth adventure." },
    { id: 53, title: "Among Us", price: 4.99, discount: 20, image: "assets/game53.jpg", category: "party", rating: 4, desc: "Unmask the impostor in a tense social deduction game." },
    { id: 54, title: "Rocket League", price: 0.00, discount: 0, image: "assets/game54.jpg", category: "sports", rating: 4, desc: "Score epic goals in high-octane car soccer." },
    { id: 55, title: "The Sims 4", price: 39.99, discount: 70, image: "assets/game55.jpg", category: "simulation", rating: 4, desc: "Shape lives in the ultimate life simulation." },
    { id: 56, title: "Star Wars Jedi: Survivor", price: 69.99, discount: 25, image: "assets/game56.jpg", category: "adventure", rating: 4, desc: "Wield the Force in a thrilling Jedi journey." },
    { id: 57, title: "Resident Evil 4 (Remake)", price: 59.99, discount: 20, image: "assets/game57.jpg", category: "action", rating: 5, desc: "Survive horror in a reimagined classic." },
    { id: 58, title: "DOOM Eternal", price: 39.99, discount: 60, image: "assets/game58.jpg", category: "action", rating: 5, desc: "Rip and tear demons in a brutal shooter." },
    { id: 59, title: "Sekiro: Shadows Die Twice", price: 59.99, discount: 50, image: "assets/game59.jpg", category: "action", rating: 5, desc: "Master the blade in a deadly shinobi tale." },
    { id: 60, title: "Dark Souls III", price: 59.99, discount: 70, image: "assets/game60.jpg", category: "rpg", rating: 5, desc: "Conquer despair in a punishing dark fantasy." },
    { id: 61, title: "Portal 2", price: 9.99, discount: 80, image: "assets/game61.jpg", category: "puzzle", rating: 5, desc: "Solve mind-bending puzzles with portals." },
    { id: 62, title: "Half-Life: Alyx", price: 59.99, discount: 40, image: "assets/game62.jpg", category: "action", rating: 5, desc: "Fight aliens in a groundbreaking VR adventure." },
    { id: 63, title: "Genshin Impact", price: 0.00, discount: 0, image: "assets/game63.jpg", category: "rpg", rating: 4, desc: "Explore Teyvat in a stunning open-world RPG." },
    { id: 64, title: "Destiny 2", price: 0.00, discount: 0, image: "assets/game64.jpg", category: "action", rating: 4, desc: "Battle across the stars in a loot-driven shooter." },
    { id: 65, title: "Warframe", price: 0.00, discount: 0, image: "assets/game65.jpg", category: "action", rating: 4, desc: "Slash and shoot as a space ninja warrior." },
    { id: 66, title: "Team Fortress 2", price: 0.00, discount: 0, image: "assets/game66.jpg", category: "action", rating: 4, desc: "Join the chaos in a timeless class-based shooter." },
    { id: 67, title: "Left 4 Dead 2", price: 9.99, discount: 80, image: "assets/game67.jpg", category: "action", rating: 5, desc: "Team up to survive a relentless zombie apocalypse." },
    { id: 68, title: "Borderlands 3", price: 59.99, discount: 70, image: "assets/game68.jpg", category: "action", rating: 4, desc: "Loot and shoot in a wild sci-fi wasteland." },
    { id: 69, title: "Fallout 4", price: 19.99, discount: 75, image: "assets/game69.jpg", category: "rpg", rating: 4, desc: "Rebuild civilization in a post-nuclear world." },
    { id: 70, title: "Fallout 76", price: 39.99, discount: 60, image: "assets/game70.jpg", category: "rpg", rating: 3, desc: "Survive online in a ravaged Appalachian wasteland." },
    { id: 71, title: "Starfield", price: 69.99, discount: 20, image: "assets/game71.jpg", category: "rpg", rating: 4, desc: "Explore the cosmos in a vast sci-fi universe." },
    { id: 72, title: "Divinity: Original Sin 2", price: 44.99, discount: 50, image: "assets/game72.jpg", category: "rpg", rating: 5, desc: "Craft your legend in a deep tactical RPG." },
    { id: 73, title: "Monster Hunter: World", price: 29.99, discount: 60, image: "assets/game73.jpg", category: "action", rating: 5, desc: "Hunt epic beasts in a vibrant living world." },
    { id: 74, title: "Monster Hunter Rise", price: 39.99, discount: 40, image: "assets/game74.jpg", category: "action", rating: 4, desc: "Ride into battle against towering monsters." },
    { id: 75, title: "Total War: Warhammer III", price: 59.99, discount: 30, image: "assets/game75.jpg", category: "strategy", rating: 4, desc: "Command armies in a fantasy war epic." },
    { id: 76, title: "Crusader Kings III", price: 49.99, discount: 40, image: "assets/game76.jpg", category: "strategy", rating: 5, desc: "Rule dynasties in a grand medieval simulation." },
    { id: 77, title: "Age of Empires IV", price: 39.99, discount: 35, image: "assets/game77.jpg", category: "strategy", rating: 4, desc: "Lead empires in a historic RTS masterpiece." },
    { id: 78, title: "FIFA 23", price: 59.99, discount: 70, image: "assets/game78.jpg", category: "sports", rating: 4, desc: "Kick off in the ultimate soccer showdown." },
    { id: 79, title: "NBA 2K24", price: 69.99, discount: 30, image: "assets/game79.jpg", category: "sports", rating: 4, desc: "Dominate the court in a basketball sim." },
    { id: 80, title: "Madden NFL 24", price: 69.99, discount: 25, image: "assets/game80.jpg", category: "sports", rating: 4, desc: "Score touchdowns in a gridiron classic." },
    { id: 81, title: "Rainbow Six Siege", price: 19.99, discount: 60, image: "assets/game81.jpg", category: "action", rating: 5, desc: "Breach and battle in a tense tactical shooter." },
    { id: 82, title: "Dead by Daylight", price: 19.99, discount: 50, image: "assets/game82.jpg", category: "horror", rating: 4, desc: "Survive or hunt in a deadly multiplayer chase." },
    { id: 83, title: "Phasmophobia", price: 13.99, discount: 20, image: "assets/game83.jpg", category: "horror", rating: 4, desc: "Hunt ghosts in a chilling co-op thriller." },
    { id: 84, title: "Civilization VI", price: 59.99, discount: 80, image: "assets/game84.jpg", category: "strategy", rating: 5, desc: "Forge a legacy in a turn-based empire builder." },
    { id: 85, title: "RimWorld", price: 34.99, discount: 10, image: "assets/game85.jpg", category: "simulation", rating: 5, desc: "Survive and thrive in a chaotic colony sim." },
    { id: 86, title: "Factorio", price: 35.00, discount: 0, image: "assets/game86.jpg", category: "simulation", rating: 5, desc: "Build and automate in an industrial sandbox." },
    { id: 87, title: "Terraria", price: 9.99, discount: 50, image: "assets/game87.jpg", category: "adventure", rating: 5, desc: "Dig, build, and fight in a 2D sandbox world." },
    { id: 88, title: "Disco Elysium", price: 39.99, discount: 60, image: "assets/game88.jpg", category: "rpg", rating: 5, desc: "Solve crimes in a unique narrative-driven RPG." },
    { id: 89, title: "Celeste", price: 19.99, discount: 50, image: "assets/game89.jpg", category: "platformer", rating: 5, desc: "Climb a mountain in a heartfelt platformer." },
    { id: 90, title: "Subnautica", price: 29.99, discount: 40, image: "assets/game90.jpg", category: "adventure", rating: 5, desc: "Dive into an alien ocean survival adventure." },
    { id: 91, title: "Subnautica: Below Zero", price: 29.99, discount: 30, image: "assets/game91.jpg", category: "adventure", rating: 4, desc: "Explore icy depths in a chilling sequel." },
    { id: 92, title: "Ark: Survival Evolved", price: 29.99, discount: 70, image: "assets/game92.jpg", category: "adventure", rating: 4, desc: "Tame dinosaurs in a prehistoric survival epic." },
    { id: 93, title: "Rust", price: 39.99, discount: 25, image: "assets/game93.jpg", category: "survival", rating: 4, desc: "Survive and raid in a harsh multiplayer world." },
    { id: 94, title: "Sea of Thieves", price: 39.99, discount: 40, image: "assets/game94.jpg", category: "adventure", rating: 4, desc: "Sail and plunder in a pirate-filled open sea." },
    { id: 95, title: "Garry's Mod", price: 9.99, discount: 50, image: "assets/game95.jpg", category: "sandbox", rating: 4, desc: "Create chaos in a limitless physics playground." },
    { id: 96, title: "Payday 2", price: 9.99, discount: 80, image: "assets/game96.jpg", category: "action", rating: 4, desc: "Pull off heists in a thrilling co-op shooter." },
    { id: 97, title: "Hitman 3", price: 59.99, discount: 50, image: "assets/game97.jpg", category: "action", rating: 4, desc: "Eliminate targets as the silent Agent 47." },
    { id: 98, title: "Control", price: 39.99, discount: 60, image: "assets/game98.jpg", category: "action", rating: 4, desc: "Unravel mysteries with supernatural powers." },
    { id: 99, title: "Frostpunk", price: 29.99, discount: 70, image: "assets/game99.jpg", category: "strategy", rating: 4, desc: "Lead a frozen city in a steampunk survival tale." },
    { id: 100, title: "Stellaris", price: 39.99, discount: 60, image: "assets/game100.jpg", category: "strategy", rating: 4, desc: "Conquer the galaxy in a grand sci-fi strategy." }
];
